#' @title Fit a Latent Variable Model.
#' @description \code{LVS.fit} computes a generalized lineatr latent variable model for multivariate bernoulli data, which assumes one latent variable.
#' @param X The training data set. It should be a matrix of binary numbers.
#' @param starting.choice Starting values can be generated by fitting model without latent variables, and applying factorial analysis to residuals to get starting values for latent variables and their coefficients (starting.choice = "res"). Another options are to use zeros as a starting values (starting.choice = "zero") or initialize starting values for latent variables with (n x 1) matrix. Defaults to "random".
#' @param p.seed A random seed for model fitting.
#' @return An object of class "gllvm" includes the following components.
LVS.fit <- function(X,starting.choice="random",p.seed=3080) {
  fit.VA <- gllvm(X,family = "binomial"("probit"),method = "VA",num.lv = 1,starting.val = starting.choice, seed = p.seed)
  return(fit.VA)
}

#' @title Compute Latent Variable Scores (LVSs).
#' @description \code{LVS.score} can compute Latent Variable Scores based on an unsupervised multivariate mixed model framework for multivariate bernoulli data that assumes one latent variable.
#' @param X The training data set. It should be a matrix of binary numbers.
#' @param Y The new data set. It should be a matrix of binary numbers.
#' @param starting.choice Starting values can be generated by fitting model without latent variables, and applying factorial analysis to residuals to get starting values for latent variables and their coefficients (starting.choice = "res"). Another options are to use zeros as a starting values (starting.choice = "zero") or initialize starting values for latent variables with (n x 1) matrix. Defaults to "random".
#' @param p.seed A random seed for model fitting.
#' @export
#' @return lvs The resulting LVSs for the new set Y.
#' @examples
#' \dontrun{
#' data(EHR)
#' sample.set = EHR$sample.set
#' res1 <- LVS.score(X = sample.set[seq(1,50),])
#' }
#' @references Jenni Niku, Wesley Brooks, Riki Herliansyah, Francis KC Hui, Sara Taskinen, and David I Warton. Efficient estimation of generalized linear latent variable models. PloS one, 14(5), 2019.

LVS.score <- function(X, Y=NULL, starting.choice="random", p.seed=3080) {
  fit.VA <- LVS.fit(X, starting.choice = starting.choice, p.seed = p.seed)
  if (is.null(Y)) {Y = X}
  pred <- predictLVs.gllvm(fit.VA, newY = Y)
  lvs <- pred$lvs
  return(lvs)
}
