#' @title Fit a Latent Variable Model
#' @description \code{LVS.fit} computes a generalized lineatr latent variable model for multivariate data, which assumes one latent variable.
#' @param X The training data set. It should be a matrix of numbers.
#' @param family distribution function for responses. Options are poisson(link = "log"), "negative.binomial" (with log link), binomial(link = "probit"), gaussian(link = "identity"), "gamma" (with log link), and "ordinal".
#' @param starting.choice Starting values can be generated by fitting model without latent variables, and applying factorial analysis to residuals to get starting values for latent variables and their coefficients (starting.choice = "res"). Another options are to use zeros as a starting values (starting.choice = "zero") or initialize starting values for latent variables with (n x 1) matrix. Defaults to "random".
#' @param p.seed A random seed for model fitting.
#' @import gllvm
#' @export
#' @return An object of class "gllvm" includes the following components.
LVS.fit <- function(X, family = "binomial", starting.choice = "random", p.seed = 3080) {
  rowsum_u = rowSums(X)
  colsum_u = colSums(X)
  Xc = X[rowsum_u!=0,]
  if (family == "binomial"){
    if (sum(colsum_u==0)>0) {stop("There is at least one column with zeros.")}
    fit.VA <- gllvm(Xc, family = "binomial"("probit"), method = "VA", num.lv = 1, starting.val = starting.choice, seed = p.seed)
  } else {
    fit.VA <- gllvm(Xc, family = family, method = "VA", num.lv = 1, starting.val = starting.choice, seed = p.seed)
  }

  return(fit.VA)
}

#' @title Latent Variable Prediction
#' @description Predicts Latent Variable Scores given a model.
#' @param Y A new data set. It should be a matrix of numbers. Default is NULL, then X will be used in prediction.
#' @param model A trained model.
#' @import gllvm
#' @export
#' @return lvs The resulting LVSs for the new set Y.
#' @examples
#' \dontrun{
#' data(EHR)
#' sample.set = EHR$sample.set
#' res1 <- predict.LVS(Y = sample.set[seq(1,50),])
#' }

predictLVS <- function(Y, model) {
  pred <- predictLVs.gllvm(model, newY = Y)
  lvs <- pred$lvs
  return(lvs)
}

#' @title Latent Variable Score
#' @description Computes Latent Variable Scores based on an unsupervised multivariate mixed model framework for multivariate bernoulli data that assumes one latent variable.
#' @param X A training data set. It should be a matrix of numbers.
#' @param Y A new data set. It should be a matrix of numbers. Default is NULL, then X will be used in prediction.
#' @param family distribution function for responses. Options are poisson(link = "log"), "negative.binomial" (with log link), binomial(link = "probit") , gaussian(link = "identity"), "gamma" (with log link), and "ordinal".
#' @param starting.choice Starting values can be generated by fitting model without latent variables, and applying factorial analysis to residuals to get starting values for latent variables and their coefficients (starting.choice = "res"). Another options are to use zeros as a starting values (starting.choice = "zero") or initialize starting values for latent variables with (n x 1) matrix. Defaults to "random".
#' @param p.seed A random seed for model fitting.
#' @import gllvm
#' @export
#' @return lvs The resulting LVSs for the new set Y.
#' @examples
#' \dontrun{
#' data(EHR)
#' sample.set = EHR$sample.set
#' res1 <- LVS.score(X = sample.set[seq(1,50),])
#' }
#' @references Jenni Niku, Wesley Brooks, Riki Herliansyah, Francis KC Hui, Sara Taskinen, and David I Warton. Efficient estimation of generalized linear latent variable models. PloS one, 14(5), 2019.

LVS.score <- function(X, Y = NULL, family = "binomial", starting.choice= "random", p.seed = 3080) {
  fit.VA <- LVS.fit(X, family = family, starting.choice = starting.choice, p.seed = p.seed)
  if (is.null(Y)) {Y = X}
  pred <- predictLVS(Y = Y, model = fit.VA)
  return(pred)
}


